apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: grafana
spec:
  config:
    log:
      mode: "console"
      level: "warn"
    auth:
      disable_login_form: false
    security:
      admin_user: admin
      admin_password: admin
